services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gereciamento_trafego
      MYSQL_USER: gereciador
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build: .
    container_name: springboot_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: gerenciamento_trafego
      MYSQL_USER: gereciador
      MYSQL_PASSWORD: root

volumes:
  mysql_data: